# Generated by Django 5.2.7 on 2025-11-05 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModificationAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_uuid', models.CharField(db_index=True, help_text='UUID of the claim, source, or connection', max_length=36)),
                ('version_number', models.IntegerField(help_text='Sequential version number (v1, v2, v3...)')),
                ('entity_type', models.CharField(choices=[('claim', 'Claim'), ('source', 'Source'), ('connection', 'Connection')], max_length=20)),
                ('is_anonymous', models.BooleanField(default=False, help_text='If True, display as [anonymous]; if user is None, display as [deleted]')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modification_attributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Modification Attribution',
                'verbose_name_plural': 'User Modification Attributions',
                'db_table': 'user_modification_attributions',
                'indexes': [models.Index(fields=['entity_uuid', 'version_number'], name='user_modifi_entity__bd3867_idx'), models.Index(fields=['user'], name='user_modifi_user_id_65cb26_idx')],
                'unique_together': {('entity_uuid', 'entity_type', 'version_number')},
            },
        ),
    ]
