# Generated by Django 5.2.7 on 2025-11-06 22:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_uuid', models.CharField(db_index=True, help_text='UUID of the claim, source, or connection being commented on', max_length=36)),
                ('entity_type', models.CharField(choices=[('claim', 'Claim'), ('source', 'Source'), ('connection', 'Connection')], max_length=20)),
                ('content', models.TextField(help_text='Comment text content')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag—hides content in UI, preserves structure')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parent_comment', models.ForeignKey(blank=True, help_text='If set, this is a reply to another comment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.comment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comments',
                'indexes': [models.Index(fields=['entity_uuid'], name='comments_entity__38706f_idx'), models.Index(fields=['user'], name='comments_user_id_8613ff_idx'), models.Index(fields=['parent_comment'], name='comments_parent__4366da_idx'), models.Index(fields=['timestamp'], name='comments_timesta_97fa2c_idx')],
            },
        ),
        migrations.CreateModel(
            name='FlaggedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_uuid', models.CharField(db_index=True, help_text='UUID of the flagged entity', max_length=36)),
                ('entity_type', models.CharField(choices=[('claim', 'Claim'), ('source', 'Source'), ('connection', 'Connection'), ('comment', 'Comment'), ('rating', 'Rating')], max_length=20)),
                ('reason', models.TextField(help_text='Explanation for why this content was flagged')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('action_taken', 'Action Taken'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, default='', help_text='Notes from staff admin review')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Staff admin who reviewed this flag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flagged Content',
                'verbose_name_plural': 'Flagged Content',
                'db_table': 'flagged_content',
                'indexes': [models.Index(fields=['entity_uuid'], name='flagged_con_entity__72b79a_idx'), models.Index(fields=['status'], name='flagged_con_status_fb93e6_idx'), models.Index(fields=['flagged_by'], name='flagged_con_flagged_858f03_idx'), models.Index(fields=['timestamp'], name='flagged_con_timesta_919d40_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_uuid', models.CharField(db_index=True, help_text='UUID of the claim, source, or connection being rated', max_length=36)),
                ('entity_type', models.CharField(choices=[('claim', 'Claim'), ('source', 'Source'), ('connection', 'Connection'), ('comment', 'Comment')], max_length=20)),
                ('dimension', models.CharField(blank=True, choices=[('confidence', 'Confidence'), ('relevance', 'Relevance')], help_text='Optional: What aspect is being rated (confidence or relevance)', max_length=20, null=True)),
                ('score', models.FloatField(help_text='Rating score from 0-100', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'db_table': 'ratings',
                'indexes': [models.Index(fields=['entity_uuid'], name='ratings_entity__1e4884_idx'), models.Index(fields=['user'], name='ratings_user_id_bd9bb9_idx'), models.Index(fields=['entity_uuid', 'dimension'], name='ratings_entity__5c4b3c_idx')],
                'unique_together': {('user', 'entity_uuid', 'entity_type', 'dimension')},
            },
        ),
    ]
