# Generated by Django 5.2.8 on 2025-11-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='If True, display as [anonymous] in public queries'),
        ),
        migrations.AddField(
            model_name='rating',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='If True, display as [anonymous] in public queries'),
        ),
    ]
