# Generated by Django 5.2.8 on 2026-01-21 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_add_is_anonymous_to_social_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_uuid', models.CharField(db_index=True, help_text='UUID of the viewed entity', max_length=36)),
                ('entity_type', models.CharField(choices=[('claim', 'Claim'), ('source', 'Source'), ('connection', 'Connection')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, default='', help_text='Session key to deduplicate views within session', max_length=40)),
                ('user', models.ForeignKey(blank=True, help_text='User who viewed (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'db_table': 'page_views',
                'indexes': [models.Index(fields=['entity_uuid'], name='page_views_entity__ff6a6a_idx'), models.Index(fields=['timestamp'], name='page_views_timesta_ae239d_idx'), models.Index(fields=['session_key', 'entity_uuid'], name='page_views_session_4bb6f2_idx')],
            },
        ),
    ]
