# Generated by Django 5.2.8 on 2026-01-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_pageview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_uuid', models.CharField(db_index=True, help_text='UUID of the entity', max_length=36, unique=True)),
                ('entity_type', models.CharField(choices=[('claim', 'Claim'), ('source', 'Source'), ('connection', 'Connection')], max_length=20)),
                ('count', models.IntegerField(default=0, help_text='Total view count')),
            ],
            options={
                'verbose_name': 'View Count',
                'verbose_name_plural': 'View Counts',
                'db_table': 'view_counts',
                'indexes': [models.Index(fields=['entity_uuid'], name='view_counts_entity__966fcd_idx')],
                'unique_together': {('entity_uuid', 'entity_type')},
            },
        ),
        migrations.DeleteModel(
            name='PageView',
        ),
    ]
