# Generated by Django 5.2.8 on 2026-01-23 01:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_viewcount_delete_pageview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='entity_type',
            field=models.CharField(choices=[('claim', 'Claim'), ('source', 'Source'), ('connection', 'Connection'), ('comment', 'Comment'), ('suggested_edit', 'Suggested Edit')], max_length=20),
        ),
        migrations.CreateModel(
            name='SuggestedEdit',
            fields=[
                ('suggestion_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID for this suggestion', primary_key=True, serialize=False)),
                ('entity_uuid', models.CharField(db_index=True, help_text='UUID of the target claim or source to modify', max_length=36)),
                ('entity_type', models.CharField(choices=[('claim', 'Claim'), ('source', 'Source')], max_length=20)),
                ('proposed_changes', models.JSONField(help_text="Dict of property: new_value pairs. E.g. {'content': 'new text'}")),
                ('rationale', models.TextField(help_text='Why this change improves the node')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_suggestions', to=settings.AUTH_USER_MODEL)),
                ('suggested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suggested Edit',
                'verbose_name_plural': 'Suggested Edits',
                'db_table': 'suggested_edits',
                'indexes': [models.Index(fields=['entity_uuid'], name='suggested_e_entity__f8a223_idx'), models.Index(fields=['status'], name='suggested_e_status_4474bf_idx'), models.Index(fields=['suggested_by'], name='suggested_e_suggest_fdd3a1_idx'), models.Index(fields=['created_at'], name='suggested_e_created_aba736_idx')],
            },
        ),
    ]
