# Generated by Django 5.2.8 on 2026-01-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_rating_entity_type_suggestededit'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestededit',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='If True, display as [anonymous] in public queries'),
        ),
    ]
