# Generated by Django 5.2.8 on 2026-02-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_suggestededit_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestededit',
            name='entity_type',
            field=models.CharField(choices=[('claim', 'Claim'), ('source', 'Source'), ('connection', 'Connection')], max_length=20),
        ),
        migrations.AlterField(
            model_name='suggestededit',
            name='entity_uuid',
            field=models.CharField(db_index=True, help_text='UUID of the target claim, source, or connection to modify', max_length=36),
        ),
    ]
