# Generated by Django 5.2.8 on 2026-02-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_suggestededit_entity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestededit',
            name='refactor_type',
            field=models.CharField(blank=True, choices=[(None, 'Simple Edit'), ('connection_restructure', 'Connection Restructure')], help_text='Type of structural refactoring, null for simple property edits', max_length=50, null=True),
        ),
    ]
