# Generated by Django 5.2.7 on 2025-10-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.CharField(db_index=True, max_length=255)),
                ('edge_type', models.CharField(max_length=100)),
                ('source_node_id', models.CharField(max_length=255)),
                ('target_node_id', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('operation', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('change_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'edge_versions',
                'indexes': [models.Index(fields=['edge_id'], name='edge_versio_edge_id_5ebc71_idx'), models.Index(fields=['timestamp'], name='edge_versio_timesta_0f86b7_idx'), models.Index(fields=['valid_from', 'valid_to'], name='edge_versio_valid_f_d8d205_idx'), models.Index(fields=['source_node_id', 'target_node_id'], name='edge_versio_source__5605ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='NodeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(db_index=True, max_length=255)),
                ('node_label', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('operation', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('change_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'node_versions',
                'indexes': [models.Index(fields=['node_id'], name='node_versio_node_id_aa22ff_idx'), models.Index(fields=['timestamp'], name='node_versio_timesta_cd2f52_idx'), models.Index(fields=['valid_from', 'valid_to'], name='node_versio_valid_f_9efee5_idx')],
            },
        ),
    ]
