# Generated by Django 5.2.7 on 2025-10-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgeversion',
            name='composite_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='edgeversion',
            name='logic_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
