# Generated by Django 5.2.7 on 2025-11-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0002_edgeversion_composite_id_edgeversion_logic_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('operation', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('change_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'claim_versions',
            },
        ),
        migrations.CreateModel(
            name='SourceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(db_index=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('publication_date', models.CharField(blank=True, max_length=100, null=True)),
                ('source_type', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('operation', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('change_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'source_versions',
            },
        ),
        migrations.DeleteModel(
            name='NodeVersion',
        ),
        migrations.AddIndex(
            model_name='claimversion',
            index=models.Index(fields=['node_id'], name='claim_versi_node_id_fb2c00_idx'),
        ),
        migrations.AddIndex(
            model_name='claimversion',
            index=models.Index(fields=['timestamp'], name='claim_versi_timesta_9f9b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='claimversion',
            index=models.Index(fields=['valid_from', 'valid_to'], name='claim_versi_valid_f_c282cc_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceversion',
            index=models.Index(fields=['node_id'], name='source_vers_node_id_9ca689_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceversion',
            index=models.Index(fields=['timestamp'], name='source_vers_timesta_a64093_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceversion',
            index=models.Index(fields=['valid_from', 'valid_to'], name='source_vers_valid_f_0772f8_idx'),
        ),
    ]
