# Generated by Django 5.2.7 on 2025-11-05 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0003_claimversion_sourceversion_delete_nodeversion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claimversion',
            name='created_by_user',
            field=models.ForeignKey(blank=True, help_text='User who created this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='edgeversion',
            name='created_by_user',
            field=models.ForeignKey(blank=True, help_text='User who created this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='created_by_user',
            field=models.ForeignKey(blank=True, help_text='User who created this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_versions', to=settings.AUTH_USER_MODEL),
        ),
    ]
