# Generated by Django 5.2.7 on 2025-11-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0004_claimversion_created_by_user_and_more'),
    ]

    operations = [
        # Add fields first, before constraints reference them
        migrations.AddField(
            model_name='claimversion',
            name='version_number',
            field=models.IntegerField(default=1, help_text='Sequential version number (v1, v2, v3...)'),
        ),
        migrations.AddField(
            model_name='edgeversion',
            name='version_number',
            field=models.IntegerField(default=1, help_text='Sequential version number (v1, v2, v3...)'),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='version_number',
            field=models.IntegerField(default=1, help_text='Sequential version number (v1, v2, v3...)'),
        ),
        migrations.AddIndex(
            model_name='claimversion',
            index=models.Index(fields=['node_id', 'version_number'], name='claim_versi_node_id_80f287_idx'),
        ),
        migrations.AddIndex(
            model_name='edgeversion',
            index=models.Index(fields=['edge_id', 'version_number'], name='edge_versio_edge_id_d667b3_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceversion',
            index=models.Index(fields=['node_id', 'version_number'], name='source_vers_node_id_8cc989_idx'),
        ),
        migrations.RemoveField(
            model_name='claimversion',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='edgeversion',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='sourceversion',
            name='created_by_user',
        ),
        # Add constraints after fields exist
        migrations.AlterUniqueTogether(
            name='claimversion',
            unique_together={('node_id', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='edgeversion',
            unique_together={('edge_id', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='sourceversion',
            unique_together={('node_id', 'version_number')},
        ),
    ]
