# Generated by Django 5.2.7 on 2025-11-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0005_alter_claimversion_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField(db_index=True, help_text='ID of the Comment in social app')),
                ('version_number', models.IntegerField(default=1, help_text='Sequential version number (v1, v2, v3...)')),
                ('user_id', models.IntegerField(help_text='User who created/modified the comment', null=True)),
                ('entity_uuid', models.CharField(max_length=36)),
                ('entity_type', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('parent_comment_id', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('operation', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('change_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment_versions',
                'indexes': [models.Index(fields=['comment_id'], name='comment_ver_comment_5f639b_idx'), models.Index(fields=['timestamp'], name='comment_ver_timesta_9f8d16_idx'), models.Index(fields=['valid_from', 'valid_to'], name='comment_ver_valid_f_711492_idx'), models.Index(fields=['comment_id', 'version_number'], name='comment_ver_comment_6ec2e5_idx'), models.Index(fields=['entity_uuid'], name='comment_ver_entity__8903cc_idx')],
                'unique_together': {('comment_id', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='RatingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_id', models.IntegerField(db_index=True, help_text='ID of the Rating in social app')),
                ('version_number', models.IntegerField(default=1, help_text='Sequential version number (v1, v2, v3...)')),
                ('user_id', models.IntegerField(help_text='User who created/modified the rating')),
                ('entity_uuid', models.CharField(max_length=36)),
                ('entity_type', models.CharField(max_length=20)),
                ('dimension', models.CharField(blank=True, max_length=20, null=True)),
                ('score', models.FloatField()),
                ('operation', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('change_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rating_versions',
                'indexes': [models.Index(fields=['rating_id'], name='rating_vers_rating__3e5e57_idx'), models.Index(fields=['timestamp'], name='rating_vers_timesta_c904d2_idx'), models.Index(fields=['valid_from', 'valid_to'], name='rating_vers_valid_f_02aaba_idx'), models.Index(fields=['rating_id', 'version_number'], name='rating_vers_rating__f76069_idx'), models.Index(fields=['entity_uuid'], name='rating_vers_entity__756f94_idx')],
                'unique_together': {('rating_id', 'version_number')},
            },
        ),
    ]
