# Generated by Django 5.2.8 on 2025-12-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0006_commentversion_ratingversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceversion',
            name='title',
            field=models.TextField(default='Untitled Source'),
        ),
    ]
