# Generated by Django 5.2.8 on 2025-12-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0007_alter_sourceversion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceversion',
            name='title',
            field=models.TextField(),
        ),
    ]
