# Generated by Django 5.2.8 on 2025-12-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0008_require_source_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceversion',
            name='url_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=2048, null=True),
        ),
    ]
