# Generated by Django 5.2.8 on 2025-12-08 21:16

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0009_add_url_normalized'),
    ]

    operations = [
        # Enable PostgreSQL trigram extension for fuzzy matching
        TrigramExtension(),

        # Add new fields
        migrations.AddField(
            model_name='claimversion',
            name='content_normalized',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='claimversion',
            name='content_search',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='title_normalized',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='title_search',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='claimversion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content_search'], name='claim_content_search_idx'),
        ),
        migrations.AddIndex(
            model_name='claimversion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content'], name='claim_content_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='sourceversion',
            index=models.Index(fields=['url_normalized'], name='source_vers_url_nor_955ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceversion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_search'], name='source_title_search_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceversion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='source_title_trgm_idx', opclasses=['gin_trgm_ops']),
        ),

        # Create triggers to auto-populate search vector fields
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER claim_version_search_update
                BEFORE INSERT OR UPDATE ON claim_versions
                FOR EACH ROW EXECUTE FUNCTION
                tsvector_update_trigger(content_search, 'pg_catalog.english', content);
            """,
            reverse_sql="DROP TRIGGER IF EXISTS claim_version_search_update ON claim_versions;"
        ),

        migrations.RunSQL(
            sql="""
                CREATE TRIGGER source_version_title_search_update
                BEFORE INSERT OR UPDATE ON source_versions
                FOR EACH ROW EXECUTE FUNCTION
                tsvector_update_trigger(title_search, 'pg_catalog.english', title);
            """,
            reverse_sql="DROP TRIGGER IF EXISTS source_version_title_search_update ON source_versions;"
        ),
    ]
