# Generated by Django 5.2.8 on 2026-02-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0010_add_search_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourceversion',
            name='author',
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='accessed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='arxiv_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='authors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='case_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='container_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='court',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='decision_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='doi',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='doi_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='edition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='editors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='issn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='issue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='jurisdiction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='legal_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='pages',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='persistent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='persistent_id_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='pmcid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='pmid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='publisher_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='thumbnail_link',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='volume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sourceversion',
            name='source_type',
            field=models.CharField(default='website', max_length=50),
        ),
        migrations.AlterField(
            model_name='sourceversion',
            name='url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddIndex(
            model_name='sourceversion',
            index=models.Index(fields=['source_type'], name='source_vers_source__2ab69e_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceversion',
            index=models.Index(fields=['doi_normalized'], name='source_vers_doi_nor_67abf9_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceversion',
            index=models.Index(fields=['publication_date'], name='source_vers_publica_787c47_idx'),
        ),
    ]
