# Generated by Django 5.2.8 on 2026-02-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0011_remove_sourceversion_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgeversion',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourceversion',
            name='source_type',
            field=models.CharField(max_length=50),
        ),
    ]
