from django.db import models

class NodeVersion(models.Model):
    """Node version history table - tracks all changes to graph nodes"""

    # Primary key (auto-generated by Django as BigAutoField)

    # Graph entity reference
    node_id = models.CharField(max_length=255, db_index=True)
    node_label = models.CharField(max_length=100)  # Node type (e.g., 'Claim')

    # Graph properties (mirrors PS_Graph_DB BasicSchema nodes)
    content = models.TextField(null=True, blank=True)

    # Temporal metadata
    OPERATION_CHOICES = [
        ('CREATE', 'Create'),
        ('UPDATE', 'Update'),
        ('DELETE', 'Delete'),
    ]
    operation = models.CharField(max_length=20, choices=OPERATION_CHOICES)
    timestamp = models.DateTimeField(auto_now_add=True, db_index=True)
    valid_from = models.DateTimeField(auto_now_add=True)
    valid_to = models.DateTimeField(null=True, blank=True)

    # Audit trail
    changed_by = models.CharField(max_length=255, null=True, blank=True)
    change_notes = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'node_versions'
        indexes = [
            models.Index(fields=['node_id']),
            models.Index(fields=['timestamp']),
            models.Index(fields=['valid_from', 'valid_to']),
        ]

    def __str__(self):
        return f"{self.node_label} {self.node_id} ({self.operation} at {self.timestamp})"


class EdgeVersion(models.Model):
    """Edge version history table - tracks all changes to graph edges"""

    # Primary key (auto-generated by Django as BigAutoField)

    # Graph entity reference
    edge_id = models.CharField(max_length=255, db_index=True)
    edge_type = models.CharField(max_length=100)  # Edge type (e.g., 'Connection')

    # Graph topology
    source_node_id = models.CharField(max_length=255)
    target_node_id = models.CharField(max_length=255)

    # Graph properties (mirrors PS_Graph_DB BasicSchema edges)
    notes = models.TextField(null=True, blank=True)

    # Temporal metadata
    OPERATION_CHOICES = [
        ('CREATE', 'Create'),
        ('UPDATE', 'Update'),
        ('DELETE', 'Delete'),
    ]
    operation = models.CharField(max_length=20, choices=OPERATION_CHOICES)
    timestamp = models.DateTimeField(auto_now_add=True, db_index=True)
    valid_from = models.DateTimeField(auto_now_add=True)
    valid_to = models.DateTimeField(null=True, blank=True)

    # Audit trail
    changed_by = models.CharField(max_length=255, null=True, blank=True)
    change_notes = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'edge_versions'
        indexes = [
            models.Index(fields=['edge_id']),
            models.Index(fields=['timestamp']),
            models.Index(fields=['valid_from', 'valid_to']),
            models.Index(fields=['source_node_id', 'target_node_id']),
        ]

    def __str__(self):
        return f"{self.edge_type} {self.edge_id} ({self.operation} at {self.timestamp})"
